---
dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
description: A new Flutter project.
dev_dependencies:
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=2.7.0 <3.0.0'
flutter:
  uses-material-design: true
name: moneysplit_flutter
publish_to: none
version: 1.0.0+1